#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Generate water_baby_blue.c / water_baby_yellow.c embedded GIFs for LVGL."""
from __future__ import annotations

import io
import math
import os
from typing import List

from PIL import Image, ImageDraw

W, H = 80, 40
SCALE = 2
W2, H2 = W * SCALE, H * SCALE
NFRAMES = 10


def lerp(a: float, b: float, t: float) -> float:
    return a + (b - a) * t


def draw_character(variant: str, phase: float) -> Image.Image:
    """Draw one frame: cute teardrop mascot (blue or yellow)."""
    if variant == "blue":
        body = (125, 211, 252, 255)
        body_mid = (96, 190, 240, 255)
        body_hi = (214, 245, 255, 235)
        outline = (2, 100, 155, 255)
        wave = (45, 170, 235, 175)
        foam = (255, 255, 255, 245)
        blush = (255, 182, 214, 215)
        tongue = (255, 120, 138, 255)
    else:
        body = (255, 224, 102, 255)
        body_mid = (255, 200, 60, 255)
        body_hi = (255, 248, 210, 230)
        outline = (165, 110, 5, 255)
        wave = (255, 190, 70, 155)
        foam = (255, 255, 255, 245)
        blush = (255, 170, 100, 215)
        tongue = (255, 130, 70, 255)

    im = Image.new("RGBA", (W2, H2), (0, 0, 0, 0))
    dr = ImageDraw.Draw(im)

    bob = int(1.5 * math.sin(phase * 1.7))
    sway = int(1.2 * math.sin(phase * 2.3))
    arm_w = 0.6 * math.sin(phase * 2.8)

    cx = W2 // 2 + sway
    cy = 44 + bob

    # --- simple wave band at bottom ---
    wy = H2 - 10
    dr.rounded_rectangle((4, wy, W2 - 4, H2 - 2), radius=6, fill=wave)
    for fx in range(8, W2, 14):
        dr.ellipse((fx, wy - 2, fx + 8, wy + 4), fill=foam)

    # --- teardrop body (main + top curl) + soft shading ---
    body_bbox = (cx - 44, cy - 26, cx + 44, cy + 24)
    dr.ellipse(body_bbox, fill=body_mid, outline=outline, width=3)
    dr.ellipse((cx - 40, cy - 22, cx + 40, cy + 20), fill=body)
    curl_bbox = (cx - 13, cy - 38, cx + 13, cy - 17)
    dr.ellipse(curl_bbox, fill=body, outline=outline, width=2)
    # shine (liquid highlights)
    dr.ellipse((cx - 30, cy - 18, cx - 10, cy + 2), fill=body_hi)
    dr.ellipse((cx + 6, cy - 10, cx + 24, cy + 8), fill=(255, 255, 255, 100))

    # --- stubby arms (up cheer) ---
    lax = cx - 52 + int(3 * arm_w)
    ray = cx + 52 - int(3 * arm_w)
    ay = cy - 4 + bob // 2
    dr.polygon(
        [(cx - 40, cy + 2), (lax, ay - 18), (cx - 32, cy - 4)],
        fill=body,
        outline=outline,
        width=2,
    )
    dr.polygon(
        [(cx + 40, cy + 2), (ray, ay - 18), (cx + 32, cy - 4)],
        fill=body,
        outline=outline,
        width=2,
    )

    # --- big glossy eyes ---
    exo = 15
    eyo = -5 + bob // 3
    for sign in (-1, 1):
        ex = cx + sign * exo
        ey = cy + eyo
        dr.ellipse((ex - 12, ey - 12, ex + 12, ey + 12), fill=(18, 22, 38, 255))
        hx = 4 if sign < 0 else 3
        dr.ellipse((ex - 6 + hx, ey - 6, ex - 1 + hx, ey - 1), fill=(255, 255, 255, 252))
        dr.ellipse((ex + 1, ey - 3, ex + 5, ey + 1), fill=(255, 255, 255, 210))

    # --- blush ---
    dr.ellipse((cx - 32, cy + 2, cx - 17, cy + 11), fill=blush)
    dr.ellipse((cx + 17, cy + 2, cx + 32, cy + 11), fill=blush)

    # --- open smile + tongue peek ---
    mouth_y = cy + 10
    dr.arc((cx - 11, mouth_y - 9, cx + 11, mouth_y + 7), start=205, end=335, fill=outline, width=2)
    dr.ellipse((cx - 5, mouth_y + 1, cx + 5, mouth_y + 7), fill=tongue)

    out = im.resize((W, H), Image.Resampling.LANCZOS)
    return out


def build_gif(variant: str) -> bytes:
    frames: List[Image.Image] = []
    for i in range(NFRAMES):
        ph = (i / NFRAMES) * 2.0 * math.pi
        frames.append(draw_character(variant, ph))
    buf = io.BytesIO()
    frames[0].save(
        buf,
        format="GIF",
        save_all=True,
        append_images=frames[1:],
        duration=90,
        loop=0,
        disposal=2,
        optimize=False,
    )
    return buf.getvalue()


def emit_c(name: str, symbol: str, data: bytes) -> str:
    guard = symbol.upper()
    lines: List[str] = [
        "/**",
        f" * @file {name}",
        f" * @brief Embedded GIF — cute water baby ({symbol.split('_')[-1]})",
        " * @note Generated by tools/gen_water_baby_assets.py",
        " * @copyright Copyright (c) Tuya Inc.",
        " */",
        "#ifdef __has_include",
        '    #if __has_include("lvgl.h")',
        "        #ifndef LV_LVGL_H_INCLUDE_SIMPLE",
        "            #define LV_LVGL_H_INCLUDE_SIMPLE",
        "        #endif",
        "    #endif",
        "#endif",
        "",
        '#if defined(LV_LVGL_H_INCLUDE_SIMPLE)',
        '    #include "lvgl.h"',
        "#else",
        '    #include "lvgl/lvgl.h"',
        "#endif",
        "",
        "#ifndef LV_ATTRIBUTE_MEM_ALIGN",
        "#define LV_ATTRIBUTE_MEM_ALIGN",
        "#endif",
        "",
        f"#ifndef LV_ATTRIBUTE_IMG_{guard}",
        f"#define LV_ATTRIBUTE_IMG_{guard}",
        "#endif",
        "",
        f"const LV_ATTRIBUTE_MEM_ALIGN LV_ATTRIBUTE_LARGE_CONST LV_ATTRIBUTE_IMG_{guard} "
        f"uint8_t {symbol}_map[] = {{",
    ]
    row = "    "
    for i, b in enumerate(data):
        row += f"0x{b:02x}, "
        if len(row) > 92:
            lines.append(row.rstrip())
            row = "    "
    if row.strip():
        lines.append(row.rstrip())
    lines.append("};")
    lines.append("")
    lines.append(f"const lv_img_dsc_t {symbol} = {{")
    lines.append(f"  .header.w = {W},")
    lines.append(f"  .header.h = {H},")
    lines.append(f"  .data_size = {len(data)},")
    lines.append(f"  .data = {symbol}_map,")
    lines.append("};")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    root = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
    out_dir = os.path.join(root, "src", "ui", "image", "emmo")
    os.makedirs(out_dir, exist_ok=True)

    for variant, sym in (("blue", "water_baby_blue"), ("yellow", "water_baby_yellow")):
        raw = build_gif(variant)
        path = os.path.join(out_dir, f"{sym}.c")
        text = emit_c(os.path.basename(path), sym, raw)
        with open(path, "w", encoding="utf-8") as f:
            f.write(text)
        print(f"Wrote {path} ({len(raw)} bytes GIF)")


if __name__ == "__main__":
    main()
