/**
 * @file tuya_config.h
 * @brief IoT specific configuration file
 *
 * @copyright Copyright (c) 2021-2024 Tuya Inc. All Rights Reserved.
 */

#ifndef TUYA_CONFIG_H_
#define TUYA_CONFIG_H_

#if __has_include("tuya_config_secrets.h")
#include "tuya_config_secrets.h"
#endif

/**
 * @brief configure the product information
 *
 * TUYA_PRODUCT_ID: PID, create on the Tuya IoT platform
 * TUYA_DEVICE_UUID: UUID, create on the Tuya IoT platform
 * TUYA_DEVICE_AUTHKEY: AUTHKEY, create on the Tuya IoT platform
 *
 * detail please refer to:
 * 1. Create the product and get the pid:
 * https://developer.tuya.com/cn/docs/iot-device-dev/application-creation?id=Kbxw7ket3aujc
 * 2. Get the open-sdk license code or module: https://platform.tuya.com/purchase/index?type=6
 *
 * warning: please replace these production information with your product id
 * and license, otherwise the demo cannot work.
 *
 */
// clang-format off
#ifndef TUYA_PRODUCT_ID
#define TUYA_PRODUCT_ID      "xvlbipu95qrs0aem"                        // Please change your product id
#endif

#ifndef TUYA_OPENSDK_UUID
#define TUYA_OPENSDK_UUID      "uuid6fbdb6724174ff3d"                    // Please change the correct uuid
#endif
#ifndef TUYA_OPENSDK_AUTHKEY
#define TUYA_OPENSDK_AUTHKEY   "wAgDp9matI5yjU2imv6HXTtEwJ6tYNPT"        // Please change the correct authkey
#endif

/**
 * @brief PINCODE for AP provisioning
 * 
 * TUYA_NETCFG_PINCODE: a random PINCODE for AP provisioning, PINCODE was generated BY TUYA PMS system!!!
 * 
 * WARNING: PINCODE is mandatory for AP provisioning
 */
// #define TUYA_NETCFG_PINCODE   "69832860"

// clang-format on

/**
 * @brief Build-time flags (set from CMakeLists.txt).
 */
#ifndef XTEINK_X4_DISABLE_LVGL
#define XTEINK_X4_DISABLE_LVGL 0
#endif
#ifndef XTEINK_X4_DISABLE_CLOUD
#define XTEINK_X4_DISABLE_CLOUD 0
#endif

/**
 * @brief Boot delay (ms) for USB Serial JTAG attach before heavy init; set 0 to disable.
 */
#ifndef X4_BOOT_DEBUG_DELAY_MS
#define X4_BOOT_DEBUG_DELAY_MS 2000U
#endif

/**
 * @brief ESP32-C3 GPIO18/19 are USB D-/D+; never init UART0 CLI on these pins.
 * @note Set 0 only if an external UART adapter uses non-USB GPIOs.
 */
#ifndef X4_USB_SERIAL_JTAG_CONSOLE
#define X4_USB_SERIAL_JTAG_CONSOLE 1
#endif

#endif
