/**
 * @file tuya_config.h
 * @brief IoT specific configuration file
 *
 * @copyright Copyright (c) 2021-2024 Tuya Inc. All Rights Reserved.
 */

#ifndef TUYA_CONFIG_H_
#define TUYA_CONFIG_H_

#if __has_include("tuya_config_secrets.h")
#include "tuya_config_secrets.h"
#endif

/**
 * @brief configure the product information
 *
 * TUYA_PRODUCT_ID: PID, create on the Tuya IoT platform
 * TUYA_DEVICE_UUID: UUID, create on the Tuya IoT platform
 * TUYA_DEVICE_AUTHKEY: AUTHKEY, create on the Tuya IoT platform
 *
 * detail please refer to:
 * 1. Create the product and get the pid:
 * https://developer.tuya.com/cn/docs/iot-device-dev/application-creation?id=Kbxw7ket3aujc
 * 2. Get the open-sdk license code or module: https://platform.tuya.com/purchase/index?type=6
 *
 * warning: please replace these production information with your product id
 * and license, otherwise the demo cannot work.
 *
 */
// clang-format off
#ifndef TUYA_PRODUCT_ID
#define TUYA_PRODUCT_ID      "xvlbipu95qrs0aem"                        // Please change your product id
#endif

#ifndef TUYA_OPENSDK_UUID
#define TUYA_OPENSDK_UUID      "uuid6fbdb6724174ff3d"                    // Please change the correct uuid
#endif
#ifndef TUYA_OPENSDK_AUTHKEY
#define TUYA_OPENSDK_AUTHKEY   "wAgDp9matI5yjU2imv6HXTtEwJ6tYNPT"        // Please change the correct authkey
#endif

/**
 * @brief PINCODE for AP provisioning
 * 
 * TUYA_NETCFG_PINCODE: a random PINCODE for AP provisioning, PINCODE was generated BY TUYA PMS system!!!
 * 
 * WARNING: PINCODE is mandatory for AP provisioning
 */
// #define TUYA_NETCFG_PINCODE   "69832860"

// clang-format on

/**
 * @brief Feature switches — edit 0/1 here, then rebuild (`tos.py build`).
 *        At least one must be 1.
 * @note Display=1 uses lightweight 1bpp gfx (no LVGL). Copy
 *       config/XTEINK_X4.config -> app_default.config for display+cloud.
 *       Cloud-only: DISPLAY=0 + XTEINK_X4_cloud_only.config.
 */
#define XTEINK_X4_ENABLE_CLOUD   1
#define XTEINK_X4_ENABLE_DISPLAY 1

#if (XTEINK_X4_ENABLE_CLOUD == 0) && (XTEINK_X4_ENABLE_DISPLAY == 0)
#error "Enable cloud and/or display in tuya_config.h (set to 1)"
#endif

/**
 * @brief X4 product power/wake gate (long-press PWR, USB-only boot -> sleep).
 *        0 = allow USB-powered boot (recommended for cloud provisioning / serial debug).
 *        1 = CrossPoint product policy (hold PWR 3s; USB-only boot enters deep sleep).
 */
#ifndef X4_ENABLE_POWER_WAKE_GATE
#if XTEINK_X4_ENABLE_DISPLAY
#define X4_ENABLE_POWER_WAKE_GATE 1
#else
#define X4_ENABLE_POWER_WAKE_GATE 0
#endif
#endif

/**
 * @brief Boot delay (ms) for USB Serial JTAG attach before heavy init; set 0 to disable.
 */
#ifndef X4_BOOT_DEBUG_DELAY_MS
#define X4_BOOT_DEBUG_DELAY_MS 2000U
#endif

/**
 * @brief ESP32-C3 GPIO18/19 are USB D-/D+; never init UART0 CLI on these pins.
 * @note Set 0 only if an external UART adapter uses non-USB GPIOs.
 */
#ifndef X4_USB_SERIAL_JTAG_CONSOLE
#define X4_USB_SERIAL_JTAG_CONSOLE 1
#endif

#endif
